### ISSUE TITLE
Not able to set dynamic url for "iconAssetName"

### ISSUE THREAD

**Issue by RajgorVK** [khanmujeeb687/flutter_pinned_shortcut#3]
For chat shortcut i need to add icon as a profile image but getting error

_```
java.io.FileNotFoundException: flutter_assets/https://......../1701926867500__IMG-20231206-WA0008.jpg
	at android.content.res.AssetManager.nativeOpenAssetFd(Native Method)
	at android.content.res.AssetManager.openFd(AssetManager.java:1011)
	at com.mintech.pinned_shortcut.flutter_pinned_shortcut.PinnedShortcutUtil.getIconFromFlutterAsset(PinnedShortcutUtil.java:141)
	at com.mintech.pinned_shortcut.flutter_pinned_shortcut.PinnedShortcutUtil.setIconFromFlutterCompat(PinnedShortcutUtil.java:130)
	at com.mintech.pinned_shortcut.flutter_pinned_shortcut.PinnedShortcutUtil.buildShortcutUsingCompat(PinnedShortcutUtil.java:117)
	at com.mintech.pinned_shortcut.flutter_pinned_shortcut.PinnedShortcutUtil.shortcutInfoCompat(PinnedShortcutUtil.java:95)
	at com.mintech.pinned_shortcut.flutter_pinned_shortcut.PinnedShortcutUtil.setShortcutItem(PinnedShortcutUtil.java:69)
	at com.mintech.pinned_shortcut.flutter_pinned_shortcut.FlutterPinnedShortcutPlugin.onMethodCall(FlutterPinnedShortcutPlugin.java:45)
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8893)
```_

Anyone please help me to set url image ad icon with this library.
Thanks in advance.

**Comment by tariqarbi03** [comment]
Please mail me .. i will share code to custi0mize this as url.
tariqarbi03@gmail.com
